### PR TITLE
Change version scheme

### PR DESCRIPTION
**Pull request by nate-double-u**
Changing from a URL based to a folder based versioning scheme.

Contributes to: https://github.com/containernetworking/cni.dev/issues/76

### CODE REVIEW

**Comment by nate-double-u** [comment]
Deploy previews:
https://deploy-preview-80--cni.netlify.app/
https://deploy-preview-80--cni.netlify.app/plugins/current/
https://deploy-preview-80--cni.netlify.app/plugins/v0.8.7/

**Comment by nate-double-u** [comment]
WIP

- [ ] redirect when visitor lands on cni.dev/plugins/ page as it won't work correctly with version dropdown
- [ ] Correct side menu

**Comment by nate-double-u** [comment]
Redirect doesn't seem to work on the deploy preview, but the redirect rules passed, and I tested it locally with the netlify cli, so it should work--if it doesn't we can open a new issue.

**Comment by nate-double-u** [comment]
I removed the link checking system as this way of versioning can lead to broken links automatically -- if for example a file is moved or removed between versions.

The link checking system wasn't ideal as is either, as it was a netlify plugin that not everyone would be able to access.

**Comment by squeed** [comment]
He @nate-double-u - this looks awesome, thanks for looking in to this!

Do we want have folders for just major and minor? Do we care about docs diffs between v0.8.7 and v0.8.6, for example?

**Comment by nate-double-u** [comment]
> Do we want have folders for just major and minor? Do we care about docs diffs between v0.8.7 and v0.8.6, for example?

That's an easy change to make now. I tend to err on the side of keeping existing information, but moving forward the team should have a discussion about which and how many versions of the documentation should be supported.

**Comment by nate-double-u** [comment]
The last force-push updates the README file to remove versioning instructions.

**Comment by nate-double-u** [comment]
Converted back to draft because I think:
- I have a better link checker solution (seems like I should restore the functionality if I'm taking the existing method away)
- I know how to deal with files being added and removed between versions (currently the menu system will generate a broken link and we'll 404)

**Comment by nate-double-u** [comment]
I've added a new link checker in the make file:
`make check-links`

I've altered the Versions dropdown menu in the plugins section. Normally it will link to the current file in the other version, but now if that file doesn't exist in the other version, it links to the top level of that version.

Example: https://deploy-preview-80--cni.netlify.app/plugins/current/main/win-overlay/ only exists from v0.8.6 and up, so the v0.6.0 and v0.7.6 entries in the menu link to the version index.

**Comment by nate-double-u** [comment]
@squeed If you're happy with this as is, I can merge it in. Or if you'd like, I can make the change to make the folders just major and minor.

**Comment by nate-double-u** [comment]
Last force-push updates the deprecation warning with the same style of code for linking to the version top level if the file has been removed between versions.

**Comment by nate-double-u** [comment]
Last force-push corrects the regex used.

**Comment by squeed** [comment]
Hey @nate-double-u (sorry for the delay!) - how much bother would it be to get rid of the last version component? If it's not to bad, we'd like to do that (so just have v0.8, v0.9, etc.)

This looks great, by the way - I think it's totally the right structure.

**Comment by nate-double-u** [comment]
> how much bother would it be to get rid of the last version component? If it's not to bad, we'd like to do that (so just have v0.8, v0.9, etc.)

Not much!

Last force-push updates to 2-digit version numbers.

**Comment by squeed** [comment]
Looks awesome to me - anyone else want to review?

**Comment by nate-double-u** [comment]
> Looks awesome to me - anyone else want to review?

I'd like to propose a lazy consensus here. If no one objects or comments by 5:00 PM PST on Friday, March 19, 2021 I'll go ahead and merge this in and start the process of dismantling the existing versioning system in favour of this one.

**Pull request merged**
