### PR TITLE
Versioning

### PR DESCRIPTION
**Pull request by nate-double-u**
cni.dev versioning system

Deploy previews: 
- https://deploy-preview-26--cni.netlify.app/ (as CURRENT)
- https://v0-8-7-cni.netlify.app/ (not deprecated, as this is CURRENT + 1, the latest released set of documents)
- https://v0-8-6-cni.netlify.app/ (marked as deprecated for example purposes. This is CURRENT + 2)

Using Kubernetes-style versioning for main site -- the CNI spec is already versioned in the documents.

Related branches:
* https://github.com/containernetworking/cni.dev/tree/release-0.8.6
* https://github.com/containernetworking/cni.dev/tree/release-0.8.7

(fixes https://github.com/containernetworking/cni.dev/issues/25)

### CODE REVIEW

**Comment by nate-double-u** [comment]
Latest version, 0.8.7 is published here: https://deploy-preview-26--cni.netlify.app/ 
v0.8.6 is published here: https://v0-8-6-cni.netlify.app/

_Note_: currently there is no difference between the two versions, this is just a mock up for the versioning system.

Versions selector works on any page (and keeps your page when switching)

Will update to the correct URL when we get the actual URL setup

**Comment by nate-double-u** [comment]
inviting @zacharysarah to review.

**Comment by nate-double-u** [comment]
Note, when setup, the release process should be fairly straight forward, we'll have to update the (config.toml file)[https://github.com/containernetworking/cni.dev/commit/2638983391e578bf14e66ead350ff8cc11ab300e], and setup a new netlify site for the new (one version old) site to live -- master will always be the lastest

**Comment by zacharysarah** [comment]
@nate-double-u 👋  At 107 changed files, this PR is hard to review without a specific scope for feedback. Are you looking for review of specific components or commits?

Based on the deploy preview, some feedback I have for versioning is to:
- Match the padding (based on eyeballing it 👀  the selector looks cramped) and vertical alignment of the version selector with the other top rail links; OR
- Right align the version selector with the GitHub and Twitter buttons

Screen Shot 2020-11-03 at 9 24 46 PM

**Comment by nate-double-u** [comment]
> @nate-double-u 👋 At 107 changed files, this PR is hard to review without a specific scope for feedback. Are you looking for review of specific components or commits?

Thanks for looking at it (and ya, 107 is too many changed files). This PR is primarily a test of the versioning system, I merged the other two PRs into this branch to help with the test, so it's a bit huge.

So the feedback I'm looking for on this PR would be specific to versioning.

> 
> Based on the deploy preview, some feedback I have for versioning is to:
> 
>     * Match the padding (based on eyeballing it 👀  the selector looks cramped) and vertical alignment of the version selector with the other top rail links; OR

I noticed that, and agree. I'm surprised that the other menu items got pushed up when I added this bit. I'll do some tinkering to fix.

> 
>     * Right align the version selector with the GitHub and Twitter buttons
> 
> Screen Shot 2020-11-03 at 9 24 46 PM

Good suggestion, will do.

**Comment by nate-double-u** [comment]
Add "(Latest)" to latest version in dropdown

**Comment by nate-double-u** [comment]
Add deprecation warning

**Comment by nate-double-u** [comment]
Both deploy previews have been updated with the versioning system: 
* https://deploy-preview-26--cni.netlify.app/ (latest version)
* https://v0-8-6-cni.netlify.app/ (one version older, deprecated tag set to true)

**Comment by nate-double-u** [comment]
- [ ] Correct deprecation warning
  Link to latest version currently incorrect.

**Comment by nate-double-u** [comment]
I've added some documentation for the [versioning process in the README](https://github.com/containernetworking/cni.dev/blob/843f4199ac3d9e4c4b8b2a97868576b6ebd59d13/README.md#versioning-the-cni-website).

**Comment by nate-double-u** [comment]
Once we're happy with the release instructions here, we should update https://github.com/containernetworking/plugins/blob/master/RELEASING.md as well.

**Comment by nate-double-u** [comment]
The versioning PR (and related branches)  have been restructured as per PR https://github.com/containernetworking/cni.dev/pull/43.

**Pull request merged**
