### PR TITLE
Migrating CNI content

### PR DESCRIPTION
**Pull request by nate-double-u**
3rd attempt at a first pass of migrating [CNI documentation](https://github.com/containernetworking/cni). (Third time's the charm, this time: simplify!)
fixes: https://github.com/containernetworking/cni.dev/issues/13

Deploy preview: https://deploy-preview-23--cni.netlify.app/

### CODE REVIEW

**Comment by nate-double-u** [comment]
Deploy preview: https://deploy-preview-23--cni.netlify.app/

Interesting pages in deploy preview:
https://deploy-preview-23--cni.netlify.app/docs/cni/
https://deploy-preview-23--cni.netlify.app/docs/cni/spec/
https://deploy-preview-23--cni.netlify.app/docs/cni/conventions/

**Comment by nate-double-u** [comment]
This is a much simpler way of versioning the CNI `SPEC` and `CONVENTIONS`. I still need to go through and correctly set links through out the copy, but I think this method of versioning these two docs should be good moving forward.

**Comment by nate-double-u** [comment]
In the https://github.com/containernetworking/cni repo, we may want to open an issue regarding building this website, and discuss how we want to manage this information (i.e., Do we want to remove the copied files from that repo? Leave them there? Edit the files there to point to their corresponding files here? etc.). I'd like to avoid duplicated content if at all possible, as it adds to the maintenance burden, but I understand that the SPEC is the main artifact of the https://github.com/containernetworking/cni repo so may have to live in both locations.

**Comment by nate-double-u** [comment]
_Content note_: 

Regarding the [`Documentation`](https://github.com/containernetworking/cni/tree/master/Documentation) folder in the main repo:
* I've left the `cnitool.md` file out here, as it's covered on the https://deploy-preview-23--cni.netlify.app/cni/cnitool/ page. 
* I've moved the `spec-upgrades.md` up into the `CNI` submenu, (https://deploy-preview-23--cni.netlify.app/cni/spec-upgrades/) rather than giving it its own subfolder.

**Comment by nate-double-u** [comment]
Inviting @zacharysarah to review.

**Comment by zacharysarah** [comment]
@nate-double-u 👋 
> the SPEC is the main artifact of the repo so may have to live in both locations.

If `SPEC.md` needs to remain in the repo, link to it from the website with some context. Dual sourcing content isn't the way to go.

**Comment by nate-double-u** [comment]
> ## Dual sourcing
> 
> > the SPEC is the main artifact of the repo so may have to live in both locations.
> 
> Dual sourcing content isn't the way to go. In my opinion, publishing content on the website would be a better developer experience.
> 
> It's better to provide actual page names ("Specification", "Conventions", via a title attribute in the front matter of each respective page) rather than reusing the file name for the link text.
> 
> If for whatever reason `SPEC.md` and `CONVENTIONS.md` need to remain at the top level of the repo, link to them from the website with some context rather than publishing the files in both places. (I recommend publishing content authoritatively on the website, though.)

During the [CNI Maintainers meeting this morning](https://docs.google.com/document/d/1SIcIzndh6DYs3cZRA8f8_CSbgzCYQxO-0lNrI7fEjhY/edit#heading=h.srmpijc6p10e) we discussed whether or not the SPEC and CONVENTIONS files should live in the [CNI repo](https://github.com/containernetworking/cni), or here. @squeed Suggested that because these files are the primary function of the [CNI repo](https://github.com/containernetworking/cni), that those files should remain there and that this website should link out to them.

**Pull request merged**
